import React from "react"
import SpotifyLogo from "../spotify-logo"
import "./style.css"

export default function AppFooter() {
  return (
    <div className="app-footer">
      <div className="app-footer-info">
        <small style={{ opacity: 0.8 }}>Generated by Top Tunes Discover</small>
        <small style={{ opacity: 0.8 }}>https://trackify-peach.vercel.app</small>
      </div>
      <SpotifyLogo color="green" />
    </div>
  )
}
